language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  
stages:
  - test
  - name: deploySnapshot
    if: branch = master
  - name: deployRelease
    if: tag IS present

before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
  
install: mvn --settings .travis/settings.xml verify -Dgpg.skip -B -V
script: skip
    
jobs:
  include:
    - stage: deploySnapshot
      addons: skip
      install: skip
      script: skip
      deploy:
        provider: script
        script: .travis/deploy.sh
        skip_cleanup: true
        on:
          repo: Hi-Fi/robotframework-javalib-base
          branch: master
    - stage: deployRelease
      addons: skip
      install: skip
      script: skip
      deploy:
        provider: script
        script: .travis/deploy.sh
        skip_cleanup: true
        on:
          repo: Hi-Fi/robotframework-javalib-base
          tags: true